apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: 337909769295.dkr.ecr.us-east-1.amazonaws.com/atp/go-app:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /test
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /test
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always