apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: 337909769295.dkr.ecr.us-east-1.amazonaws.com/atp:go-app # TODO: Create separate repos
        env:
        - name: ALPACA_API_KEY
          valueFrom:
            secretKeyRef:
              name: alpaca-credentials
              key: api-key
        - name: ALPACA_API_SECRET
          valueFrom:
            secretKeyRef:
              name: alpaca-credentials
              key: api-secret
        - name: KAFKA_BROKER
          value: "kafka-service:9092" # Update with your Kafka service DNS
