CREATE TABLE performance_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE CASCADE,
  -- Returns
  total_return_pct DECIMAL(10,4),
  benchmark_return_pct DECIMAL(10,4),
  compounding_annual_return DECIMAL(10,4),
  alpha DECIMAL(10,6),
  beta DECIMAL(10,6),
  -- Risk
  sharpe_ratio DECIMAL(10,4),
  sortino_ratio DECIMAL(10,4),
  max_drawdown_pct DECIMAL(10,4),
  max_drawdown_duration_days INT,
  drawdown_recovery_days INT,
  volatility_annual DECIMAL(10,4),
  annual_variance DECIMAL(10,4),
  information_ratio DECIMAL(10,4),
  tracking_error DECIMAL(10,6),
  treynor_ratio DECIMAL(10,4),
  probabilistic_sharpe_ratio DECIMAL(10,4),
  value_at_risk_99 DECIMAL(10,4),
  value_at_risk_95 DECIMAL(10,4),
  -- Trades
  total_trades INT,
  winning_trades INT,
  losing_trades INT,
  win_rate_pct DECIMAL(10,4),
  loss_rate_pct DECIMAL(10,4),
  avg_win_pct DECIMAL(10,4),
  avg_loss_pct DECIMAL(10,4),
  profit_loss_ratio DECIMAL(10,4),
  expectancy DECIMAL(10,4),
  total_fees DECIMAL(20,4),
  avg_trade_duration VARCHAR(50),
  max_consecutive_wins INT,
  max_consecutive_losses INT,
  largest_win DECIMAL(20,4),
  largest_loss DECIMAL(20,4),
  avg_mae DECIMAL(10,6),
  avg_mfe DECIMAL(10,6),
  -- Portfolio
  start_equity DECIMAL(20,4),
  end_equity DECIMAL(20,4),
  net_profit DECIMAL(20,4),
  portfolio_turnover DECIMAL(10,4),
  estimated_capacity DECIMAL(20,4),
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW()
);
