apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-parameter-store
  namespace: default
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alpaca-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: alpaca-credentials
  data:
  - secretKey: ALPACA_API_KEY
    remoteRef:
      key: /atp/alpaca-credentials
      property: ALPACA_API_KEY
  - secretKey: ALPACA_API_SECRET
    remoteRef:
      key: /atp/alpaca-credentials
      property: ALPACA_API_SECRET