---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alpaca-credentials
  namespace: default
spec:
  encryptedData:
    ALPACA_API_KEY: AgDFkkcma0ogwHKfHQzptexB3TeHFUcJtdqJeMQXrzX388QdlPqKCTWVJiPre+A/q6TO4MJup3u5m5Nun/VH9ytNlyGzkikwCqbdZr/3Bfsvh1lOPglA9ovyh/I6XmGEw7DTV3+pmsJurOwqbVpHeYI+bWU9uADiuHHEgxNO0zlJhq5jdgoI8sURd9sgNawh+ueuwUseq7EfbRgumqSgMDWP0bRsoRQK9AGurTUXqwgNstcIl7/eM2e2wlOVX+s1fF4NN1k5D/L2UqZINHY+WvGNo8TYPjenaKU4x0zl4nn+gDOfpoI/LtIzDaNobhXygSf5R1DaQkrVhlqkR1RCVWJ0HM8/hNyDTRCYk8ZfBleipCr4pBe9q1vbzvD+W/42izDKGlzjjDr0jB1T/GOISZQSMxOOGVF8ndhYf7D13XoonsV7s0aIrElPwk6cfh5OCMbIKNu5tlSGJIAXMp/xCCfFxumdRrwhaV9/rbTLRoeYN8NA2QfkdxaGt9h9E7CJ4q5aOtAVWmwh50LPWHF1q3V5mqNKqMjZ8FASyItqDreQwa1ZO7dlZYkIOVfmpeopbQhybcNAqGZuYXCK/GVYeNvKFr3ynFrx6VOpG/wDEqrOdDKRBh4BzOSZqTR6++F8wwtEo96y+i6ywbyMHP1bw0Am+tIJdipnoAue2Byfh76rsc3k7Uq1FunWG5ObtesTs3Gux4jUWi2KkOqc
    ALPACA_API_SECRET: AgC2ZKDKNaRo/bmcrQh3s7/vyAfA9aNdJ9hQN4ryWSJn4iH5tpXiNzKB/MKFedEGkjO/nMyER85vMBwXBOm1obkUqgFUSq/3pNaJ+g8kT5TD+25m0jcAQ9mNv7e69lSqnPMfOubFKhPHWXhQnO9+f339GepMBYZ29V+sKyqO7IpMwmOdm4Og6feuED8HTnNmnfm8bOIM07ExyFWZcgoBtvzBANRgZ3gwaHX7MwdpDjvEyqOSgw9vdb1zu4tycXhM3IqEFozPBK9akmLxLvPtcXV6oiylBwrlyMln2x44glGV/kUfqDgvJ46dWOyaHEzIDw2gKwbNunx3PGdlFRMxJiuWDqcGU0xva9qJOhr1HB19ywGVGMGQyebyhY3YjMzdaU2qihJe9bYHOS8L8SJKxHJhpEx8S8poQYfMuIo1wXK8l6VHXTponrX7qb501nzEfplXaxl+I6vz6GyYUeN2XNOWuPsrx9IFzhniAkBXrbGGXvZ9Lo7qqodC6XdnyY49qHUTFf6IPUfIVqmPZsHJLz8zXWal5OVeev0Pa1nxLW0e56Vf1DA9cka3Vkpx9PeJPH0lENquhAI+QzKQd+71WivF0cC6E9F3ISxtHknU00FrrkevcVEViKOQQzEqFbxeceKlqcObAc85GNx8KSDcqlVR3PPdWmSFYNzYcXzdtENoboHO+UTJaHQLmFioPOSc7Ros+rB89jj/h1efBFHc
  template:
    metadata:
      name: alpaca-credentials
      namespace: default
    type: Opaque
