apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: 337909769295.dkr.ecr.us-east-1.amazonaws.com/atp/go-data:latest
        ports:
        - containerPort: 8080
        livenessProbe: # Restart container if it becomes unhealthy
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe: # Add pod to the service only after it's ready
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
