apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: backend-user
          key: backend-username
    - name: ALPACA_API_KEY
      valueFrom:
        secretKeyRef:
          name: alpaca-credentials
          key: ALPACA_API_KEY
    - name: ALPACA_API_SECRET
      valueFrom:
        secretKeyRef:
          name: alpaca-credentials
          key: ALPACA_API_SECRET