[supervisord]
nodaemon=true
logfile=/logs/supervisord.log

[program:celery]
command=celery -A celery_worker worker --loglevel=info --logfile=/logs/celery.log
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:api]
command=uvicorn app:app --host 0.0.0.0 --port 8082
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null
